version: '3'
services:
  api:
   build: ./container-api/
   restart: always
   env_file:
   - .env
   ports:
   - "9999:5432"
   depends_on:
   - db
  db:
   image: postgres
   restart: always
   env_file:
   - .env
   ports:
    - "9999:5432"
   volumes:
   - /home/db/test:/var/lib/postgresql/data:rw
   - ./container-db/initdb.d:/docker-entrypoint-initdb.d